version: '3'
services:
  client:
    build: ./client
  client-proxy:
    build: ./client-proxy
    ports:
      - '8001:8001'
    volumes:
      - ./client-proxy/envoy.yaml:/etc/envoy.yaml
  server:
    build: ./server
  server-proxy:
    build: ./server-proxy
    ports:
      - '8002:8001'
    volumes:
      - ./server-proxy/envoy.yaml:/etc/envoy.yaml
