version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "8001:8001"
      - "9000:9000"
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy.yaml
  client:
    build: ./client
  server:
    build: ./server
